version: "3.3"
   
volumes:
  pgdata:

services:
  db:
    image: hyperledger/explorer-db:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/opt/data
      - ./restore.sh:/opt/restore.sh
    container_name: explorerdb
    hostname: explorerdb
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
  graph-db:
    image: neo4j:latest
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs 
      - ./data:/var/lib/neo4j/import
    container_name: neo4j
    hostname: neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
        - "7474:7474"
        - "7687:7687"
